name: Update grills.json

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  PYTHON_VERSION: "3.12"

jobs:
  update-grills-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run dump_grills.py
        id: run-script
        run: |
          GRILLS_JSON="pytboss/grills.json"
          echo "Running scripts/dump_grills.py"
          python scripts/dump_grills.py > "$GRILLS_JSON"

          if ! git diff --exit-code "$FILE_TO_UPDATE"; then
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          else
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create PR
        id: create-pr
        if: steps.run-script.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.BOT_PAT }}
          commit-message: "Automated: Update grills.json"
          title: "Automated: Update grills.json"
          body: |
            Update grills.json with the latest definitions.

            This PR was automatically generated by a GitHub Action.
          push-to-fork: dknowles-bot/pytboss
          base: main
          branch: grills-json-${{ github.run_number }}
          delete-branch: true
          labels: enhancement
